# Generated by Django 5.1.5 on 2025-02-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='events_images/default.jpg', upload_to='events_images/'),
        ),
    ]
